# Generated by Django 4.2.7 on 2023-11-04 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.IntegerField()),
                ('item_type', models.CharField(db_index=True, max_length=50)),
                ('author', models.CharField(max_length=100, null=True)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('url', models.URLField(max_length=500, null=True)),
                ('title', models.CharField(max_length=200, null=True)),
                ('text', models.TextField(null=True)),
                ('score', models.BigIntegerField(default=0, null=True)),
                ('parent_id', models.IntegerField(null=True, verbose_name='Parent ID')),
            ],
            options={
                'verbose_name': 'All Items',
                'verbose_name_plural': 'All Items',
                'ordering': ['-time'],
            },
        ),
    ]
