# Generated by Django 4.2.7 on 2023-11-05 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_item_delete_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='fetched',
            field=models.BooleanField(default=False),
        ),
    ]
